In [153]:
import numpy as np
import pandas as pd
rng = np.random.default_rng(seed=12345)

# ndarray对象内部

In [36]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

### numpy数据类型体系

In [37]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [38]:
np.issubdtype(floats.dtype, np.floating)

True

#### mro方法查看类型的所有父类

In [39]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [40]:
np.issubdtype(ints.dtype, np.number)

True

# 高级数组操作

### 重新设置数组维度 reshape

In [41]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

#### 指定排列方向

In [42]:
arr.reshape((4, 2),order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [43]:
arr.reshape((4, 2),order='f')

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

#### 多次reshape

In [44]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### 一个维度为-1，自动推断

In [45]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### 利用已有shape

In [46]:
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 高维到一维 ravel和flatten

In [47]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [48]:
# 不复制原数据
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
# 复制原数据
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### c顺序 vs fortran顺序

In [50]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### 连接和截断数组

#### concatenate

In [53]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### vstack 和hstack

In [55]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### split

In [57]:
arr = rng.standard_normal((5, 2))
arr

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

In [58]:
first, second, third = np.split(arr, [1, 3])

In [59]:
first

array([[-1.42382504,  1.26372846]])

In [60]:
second

array([[-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465]])

In [61]:
third

array([[-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

#### r_和c_

In [62]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = rng.standard_normal((3, 2))
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 2.34740965,  0.96849691],
       [-0.75938718,  0.90219827],
       [-0.46695317, -0.06068952]])

In [63]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 2.34740965,  0.96849691,  3.        ],
       [-0.75938718,  0.90219827,  4.        ],
       [-0.46695317, -0.06068952,  5.        ]])

### 重复元素：tile和repeat

#### 一维repeat

In [64]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [65]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [66]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

#### 多维沿着轴repeat

In [67]:
arr = rng.standard_normal((2, 2))
arr

array([[ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899]])

In [68]:
arr.repeat(2, axis=0)

array([[ 0.78884434, -1.25666813],
       [ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899],
       [ 0.57585751,  1.39897899]])

In [69]:
arr.repeat([2, 3], axis=0)

array([[ 0.78884434, -1.25666813],
       [ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899],
       [ 0.57585751,  1.39897899],
       [ 0.57585751,  1.39897899]])

In [70]:
arr.repeat([2, 3], axis=1)

array([[ 0.78884434,  0.78884434, -1.25666813, -1.25666813, -1.25666813],
       [ 0.57585751,  0.57585751,  1.39897899,  1.39897899,  1.39897899]])

#### tile指定轴重复次数

In [71]:
arr

array([[ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899]])

In [72]:
np.tile(arr, 2)

array([[ 0.78884434, -1.25666813,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899]])

In [73]:
arr

array([[ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899]])

In [74]:
np.tile(arr, (2, 1))

array([[ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899],
       [ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899]])

In [75]:
np.tile(arr, (3, 2))

array([[ 0.78884434, -1.25666813,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
       [ 0.78884434, -1.25666813,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
       [ 0.78884434, -1.25666813,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899]])

### take读取，put修改数据

#### 一维读取和修改

In [76]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [77]:
arr.take(inds)

array([700, 100, 200, 600])

In [78]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [79]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

#### 多维读取数据

In [80]:
inds = [2, 0, 2, 1]
arr = rng.standard_normal((2, 4))
arr

array([[ 1.32229806, -0.29969852,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -1.34360107, -0.08168759]])

In [81]:
arr.take(inds, axis=1)

array([[ 0.90291934,  1.32229806,  0.90291934, -0.29969852],
       [-1.34360107, -0.15818926, -1.34360107,  0.44948393]])

# 传播

### 二维数组中的传播

#### 纵向传播

In [82]:
arr = np.arange(5)
arr*4

array([ 0,  4,  8, 12, 16])

In [83]:
arr = rng.standard_normal((4, 3))
arr.mean(0)

array([0.1205802 , 0.24301074, 0.14436756])

In [84]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 1.60415973,  2.37514869,  0.63299379],
       [ 0.708053  , -1.20199905, -1.35375584],
       [-1.53287221,  0.29853609,  0.60757184],
       [-0.77934052, -1.47168573,  0.11319021]])

In [85]:
demeaned.mean(0)

array([ 5.55111512e-17, -1.11022302e-16,  0.00000000e+00])

#### 横向传播

In [86]:
arr

array([[ 1.72473993,  2.61815943,  0.77736134],
       [ 0.8286332 , -0.95898831, -1.20938829],
       [-1.41229201,  0.54154683,  0.7519394 ],
       [-0.65876032, -1.22867499,  0.25755777]])

In [87]:
row_means = arr.mean(1)
row_means.shape

(4,)

In [88]:
row_means.reshape((4, 1))

array([[ 1.70675357],
       [-0.44658113],
       [-0.03960193],
       [-0.54329251]])

In [89]:
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([-1.48029737e-16,  3.70074342e-17,  0.00000000e+00,  3.70074342e-17])

### np.newaxis指定要传播的轴

In [90]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [91]:
arr_1d = rng.standard_normal(3)
arr_1d[:, np.newaxis]

array([[ 0.31290292],
       [-0.13081169],
       [ 1.26998312]])

In [92]:
arr_1d[np.newaxis, :]

array([[ 0.31290292, -0.13081169,  1.26998312]])

#### 三维数组

In [93]:
arr = rng.standard_normal((3, 4, 5))
depth_means = arr.mean(2)
depth_means

array([[ 0.04314136,  0.27468984, -0.18852342, -0.20137996],
       [-0.57324159, -0.54671393,  0.11832783, -0.63005577],
       [ 0.09723001,  0.59537117,  0.03307289, -0.6002202 ]])

In [94]:
depth_means.shape

(3, 4)

In [95]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[ 4.44089210e-17, -1.11022302e-17,  8.88178420e-17,
        -1.66533454e-17],
       [ 2.22044605e-17, -4.44089210e-17, -2.22044605e-17,
        -4.44089210e-17],
       [ 4.44089210e-17,  6.66133815e-17,  0.00000000e+00,
         8.88178420e-17]])

In [96]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)
    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

### 通过传播来设置数组值

In [97]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [98]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [99]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

# 高级ufunc用法

### ufunc实例方法

#### 求和

In [100]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [101]:
arr.sum()

45

#### 比较大小

In [102]:
my_rng = np.random.default_rng(12346) # for reproducibility
arr = my_rng.standard_normal((5, 5))
arr

array([[-0.903889  ,  0.15713146,  0.89761199, -0.76219554, -0.17625556],
       [ 0.05303172, -1.62844028, -0.17753333,  1.96360352,  1.78125478],
       [-0.87971984, -1.69847913, -1.81891091,  0.11895453, -0.44409513],
       [ 0.76911421, -0.03433778,  0.39252776,  0.75891811, -0.07045967],
       [ 1.04984775,  1.02967072, -0.42005533,  0.78626627,  0.96124929]])

In [103]:
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [104]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

#### 累加

In [105]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

#### outer 升维

In [106]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [107]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [108]:
x, y = rng.standard_normal((3, 4)), rng.standard_normal(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

#### reduceat 分段聚合

In [109]:
arr = np.arange(10)

np.add.reduceat(arr, [0, 5, 8])


array([10, 18, 17])

In [110]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [111]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### 编写新的ufunc

In [112]:
def add_elements(x, y):
        return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

#### 指定返回的数据类型

In [113]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

#### 自定义的速度比原生基于c的慢

In [114]:
arr = rng.standard_normal(10000)
%timeit add_them(arr, arr)

2.58 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [115]:
%timeit np.add(arr, arr)

3.15 µs ± 245 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 结构化和记录数组

### 结构化数组

In [116]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [117]:
sarr[0]

(1.5, 6)

In [118]:
sarr[0]['y']

6

In [119]:
sarr['x']

array([1.5       , 3.14159265])

### 内嵌数据类型和多维字段

#### 例1

In [120]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [121]:
arr[0]['x']

array([0, 0, 0])

In [122]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### 例2

In [123]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [124]:
data['y']

array([5, 6], dtype=int32)

In [125]:
data['x']['a']

array([1., 3.])

# 排序

### 数组

#### 数组对象调用sort方法不产生新的数组

In [126]:
arr = rng.standard_normal(6)
arr.sort()
arr

array([-1.15533009, -0.93190851, -0.52183471, -0.47451353, -0.16487175,
        0.03003636])

In [127]:
arr = rng.standard_normal((3, 5))
arr[:, 0].sort()
arr

array([[-1.19558568,  0.46914309, -0.35978023,  1.03591571,  0.22672235],
       [-0.74479832, -0.59313793, -1.055009  , -0.06826983,  0.45795065],
       [-0.07002967,  0.14616063, -0.9943506 ,  1.14361991,  0.5025894 ]])

#### numpy.sort产生新数组

In [128]:
arr = rng.standard_normal(5)
arr

array([ 0.89812774, -1.17039613, -0.26857518, -0.79595321,  1.45222994])

In [129]:
np.sort(arr)
arr

array([ 0.89812774, -1.17039613, -0.26857518, -0.79595321,  1.45222994])

#### 沿轴排序

In [130]:
arr = rng.standard_normal((3, 5))
arr

array([[-0.25351976,  2.11834357,  0.36340947, -0.62451153,  1.12789103],
       [ 1.61635997, -0.22872843, -0.62009458, -0.11432382, -1.20673403],
       [-1.08719255, -2.15177088, -0.62873036, -1.31990725,  0.08304824]])

In [131]:
arr.sort(axis=1)
arr

array([[-0.62451153, -0.25351976,  0.36340947,  1.12789103,  2.11834357],
       [-1.20673403, -0.62009458, -0.22872843, -0.11432382,  1.61635997],
       [-2.15177088, -1.31990725, -1.08719255, -0.62873036,  0.08304824]])

#### 调整顺序方法

In [132]:
arr[:, ::-1]

array([[ 2.11834357,  1.12789103,  0.36340947, -0.25351976, -0.62451153],
       [ 1.61635997, -0.11432382, -0.22872843, -0.62009458, -1.20673403],
       [ 0.08304824, -0.62873036, -1.08719255, -1.31990725, -2.15177088]])

### 间接排序

#### 根据数字大小排序

In [133]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [134]:
values[indexer]

array([0, 1, 2, 3, 5])

In [135]:
arr = rng.standard_normal((3, 5))
arr[0] = values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.75033171, -2.1267841 , -1.39102406, -0.49224676,  0.45052254],
       [ 0.89260435, -1.04793665,  0.95532342,  0.29355494,  0.53794446]])

In [136]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-2.1267841 , -1.39102406,  0.45052254, -0.49224676, -0.75033171],
       [-1.04793665,  0.95532342,  0.53794446,  0.29355494,  0.89260435]])

#### 根据字母先后

In [137]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4])

In [138]:
list(zip(last_name[sorter], first_name[sorter]))

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

### 替代排序算法

In [139]:
values = np.array(['2:first', '2:second', '1:first', '1:second',
                   '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer


array([2, 3, 4, 0, 1])

In [140]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

### 部分排序

In [141]:
rng = np.random.default_rng(12345)
arr = rng.standard_normal(20)
arr

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,
        2.34740965,  0.96849691, -0.75938718,  0.90219827, -0.46695317,
       -0.06068952,  0.78884434, -1.25666813,  0.57585751,  1.39897899])

In [142]:
np.partition(arr, 3)

array([-1.95286306, -1.42382504, -1.3677927 , -1.25666813, -0.87066174,
       -0.75938718, -0.74088465, -0.06068952,  0.36105811, -0.07534331,
       -0.25917323, -0.46695317,  0.57585751,  0.90219827,  0.96849691,
        0.6488928 ,  0.78884434,  1.26372846,  1.39897899,  2.34740965])

In [143]:
indices = np.argpartition(arr, 3)
indices

array([ 9,  0,  6, 17,  2, 12,  5, 15,  8,  4,  3, 14, 18, 13, 11,  7, 16,
        1, 19, 10])

In [144]:
arr.take(indices)

array([-1.95286306, -1.42382504, -1.3677927 , -1.25666813, -0.87066174,
       -0.75938718, -0.74088465, -0.06068952,  0.36105811, -0.07534331,
       -0.25917323, -0.46695317,  0.57585751,  0.90219827,  0.96849691,
        0.6488928 ,  0.78884434,  1.26372846,  1.39897899,  2.34740965])

### 已排序数组中查找元素

In [145]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)


3

In [146]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [147]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])

array([0, 3])

In [149]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [150]:
data = np.floor(rng.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([ 815., 1598., 3401., 4651., 2664., 8157., 1932., 1294.,  916.,
       5985., 8547., 6016., 9319., 7247., 8605., 9293., 5461., 9376.,
       4949., 2737., 4517., 6650., 3308., 9034., 2570., 3398., 2588.,
       3554.,   50., 6286., 2823.,  680., 6168., 1763., 3043., 4408.,
       1502., 2179., 4743., 4763., 2552., 2975., 2790., 2605., 4827.,
       2119., 4956., 2462., 8384., 1801.])

In [151]:
labels = bins.searchsorted(data)
labels

array([2, 3, 3, 3, 3, 4, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 4,
       3, 4, 3, 3, 3, 3, 1, 4, 3, 2, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 3])

In [154]:
pd.Series(data).groupby(labels).mean()

1      50.000000
2     803.666667
3    3079.741935
4    7635.200000
dtype: float64

# 使用Numba写快速的numpy函数

In [155]:
import numpy as np

def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count
x = rng.standard_normal(10_000_000)
y = rng.standard_normal(10_000_000)
%timeit mean_distance(x, y)

4.54 s ± 1.45 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [156]:
 %timeit (x - y).mean()

48.2 ms ± 9.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [157]:
import numba as nb

numba_mean_distance = nb.jit(mean_distance)
%timeit numba_mean_distance(x, y)

44 ms ± 20.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# 或者使用注解的方法
@nb.jit
def numba_mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [ ]:
from numba import float64, njit
@njit(float64(float64[:], float64[:]))
def mean_distance(x, y):
    return (x - y).mean()

#### 使用numba创建自定义的ufunc

In [158]:
from numba import vectorize
@vectorize
def nb_add(x, y):
    return x + y
x = np.arange(10)
nb_add(x, x)
nb_add.accumulate(x, 0)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

# 高级数组输入和输出

### 内存映射文件

In [159]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+',shape=(10000, 10000))
mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
section = mmap[:5]

In [160]:
section[:] = rng.standard_normal((5, 10000))
mmap.flush()
mmap

NameError: ignored

In [ ]:
del mmap

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

In [ ]:
# 本机删除磁盘文件
%xdel mmap
!rm mymmap

# 性能注意

### 连续内存的重要性

In [161]:
arr_c = np.ones((100, 10000), order='C')
arr_f = np.ones((100, 10000), order='F')
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [ ]:
arr_f.flags

In [ ]:
arr_f.flags.f_contiguous

#### 观察时间

In [ ]:
%timeit arr_c.sum(1)

In [ ]:
%timeit arr_f.sum(1)

#### 转换

In [ ]:
arr_f.copy('C').flags

In [ ]:
arr_c[:50].flags.contiguous

In [ ]:
arr_c[:, :50].flags